apiVersion: v2
name: pghero-controller
description: Kubernetes controller for managing PgHero database connections
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - pghero
  - postgres
  - postgresql
  - database
  - monitoring
  - controller
home: https://github.com/mithucste30/pghero-controller
sources:
  - https://github.com/mithucste30/pghero-controller
  - https://github.com/ankane/pghero
maintainers:
  - name: mithucste30
icon: https://raw.githubusercontent.com/ankane/pghero/master/app/assets/images/pghero.png

dependencies:
  - name: postgresql
    version: "~16.2.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
